from .config import config
from .database import DATETIME
from .database import database
from .database import database_close
from .jsonlogging import logger
from .utils import parseint

import argparse
import importlib
import os
import re
from datetime import datetime
from datetime import UTC
from functools import reduce
from operator import itemgetter
from pathlib import Path

def get_commands() -> dict:
    def validate(inst):
        must_have = ('NAME', 'DESC', '__call__')
        for k in must_have:
            if not hasattr(inst, k):
                return False
        return True

    commands = {
            Env.NAME: Env(),
            Init.NAME: Init(),
            Make.NAME: Make(),
            Migrate.NAME: Migrate(),
            PAT.NAME: PAT(),
            }

    # Get app command path
    path = Path().cwd() / 'commands'
    if not path.exists():
        return commands

    for file in path.iterdir():
        if not file.is_file():
            continue
        if file.suffix != '.py':
            continue

        module_name = f'commands.{file.stem}'
        module = importlib.import_module(module_name)

        try:
            cls_name = _snake_to_camel(file.stem)
            inst = getattr(module, cls_name)()
            if isinstance(inst, Command):
                if validate(inst):
                    commands[inst.NAME] = inst
        except Exception as e:
            logger.error(e)
            logger.exception(e)

    return commands

def _camel_to_snake(value: str) -> str:
    value = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', value)
    value = re.sub(r'([a-z\d])([A-Z])', r'\1_\2', value)
    return value.lower()

def _get_migrations():
    def find(state, migration):
        for idx, item in enumerate(state):
            if item['migration'] == migration:
                return idx
        return -1

    def validate(module):
        must_have = ('NAME', 'migrate', 'rollback')
        for k in must_have:
            if not hasattr(module, k):
                return False
        return True

    # Get migrations
    state = []
    db = database()

    try:
        sql = '''
            SELECT
            *
            FROM pyteet_migrations
        '''
        state = db.fetchall(sql)
    except:
        logger.debug(f'pyteet_migrations does not exist, create.')
        if db.driver == 'mysql':
            sql = '''
                CREATE TABLE pyteet_migrations (
                    id bigint unsigned NOT NULL AUTO_INCREMENT,
                    migration varchar(255) NOT NULL,
                    batch bigint unsigned NOT NULL,
                    created_at timestamp NULL DEFAULT NULL,
                    updated_at timestamp NULL DEFAULT NULL,
                    PRIMARY KEY (id)
                )
            '''
        if db.driver == 'postgres':
            sql = '''
                CREATE TABLE pyteet_migrations (
                    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    migration varchar(255) NOT NULL,
                    batch bigint NOT NULL,
                    created_at timestamp NULL DEFAULT NULL,
                    updated_at timestamp NULL DEFAULT NULL
                )
            '''
        if db.driver == 'sqlite':
            sql = '''
                CREATE TABLE pyteet_migrations (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    migration TEXT NOT NULL,
                    batch INTEGER NOT NULL,
                    created_at TEXT NULL,
                    updated_at TEXT NULL
                )
            '''
        db.execute(sql)

    # Find migrations
    path = Path().cwd() / 'migrations'
    if path.exists():
        for file in path.iterdir():
            if not file.is_file():
                continue
            if file.suffix != '.py':
                continue
            module_name = f'migrations.{file.stem}'
            module = importlib.import_module(module_name)
            if not validate(module):
                continue
            migration = getattr(module, 'NAME')
            idx = find(state, migration)
            if idx >= 0:
                state[idx]['processed'] = True
            else:
                state.append({
                    'id': '',
                    'migration': migration,
                    'batch': '',
                    'processed': False,
                    'module': module_name,
                    })

    # Filter out states with UNKNOWN processed state
    state = [x for x in state if 'processed' in x]

    # Sort
    state = sorted(state, key=itemgetter('migration'))
    return state

def _pluralize(word: str) -> str:
    # Simle pluralize
    # https://www.geeksforgeeks.org/python/python-program-to-convert-singular-to-plural/
    # Check if word is ending with s,x,z or is
    # ending with ah, eh, ih, oh,uh,dh,gh,kh,ph,rh,sh,th
    word = str(word).strip()
    if re.search(r'[sxz]$', word) or re.search(r'[aeioudgkprst]h$', word):
        # Make it plural by adding es in end
        return word + 'es'
    # Check if word is ending with y
    elif re.search(r'y$', word):
        # Make it plural by removing y from end adding ies to end
        return re.sub(r'y$', 'ies', word)
    # In all the other cases
    else:
        # Make the plural of word by adding s in end
        return word + 's'

def _snake_to_camel(value: str) -> str:
    segments = value.split('_')
    segments = [x.capitalize() for x in segments]
    return ''.join(segments)

class Command:
    pass

class Env(Command):

    NAME = 'env'
    DESC = 'Print app.env config value'

    def __call__(self, args: list | None=[]):
        parser = argparse.ArgumentParser(
                description=self.DESC,
                usage=self.NAME)
        parsed = parser.parse_args(args)
        print(config('app.env'))

class Init(Command):

    NAME = 'init'
    DESC = 'Initialize a new Pyteet project'

    def __call__(self, args: list | None=[]):
        parser = argparse.ArgumentParser(
                description=self.DESC,
                usage=self.NAME)
        parsed = parser.parse_args(args)

        tpl_root = Path(__file__).resolve().parent / 'templates'
        proj_root = Path().cwd()

        # Include .gitignore
        gitignore = proj_root / '.gitignore'
        if not gitignore.exists():
            with open(tpl_root / 'gitignore', 'r') as r:
                contents = r.read()
            with open(gitignore.as_posix(), 'w') as w:
                w.write(contents)
                print(f'created: {gitignore.as_posix()}')

        # Include app.ini.example
        app_ini_example = proj_root / 'app.ini.example'
        if not app_ini_example.exists():
            with open(tpl_root / 'app.ini.example', 'r') as r:
                contents = r.read()
            with open(app_ini_example.as_posix(), 'w') as w:
                w.write(contents)
                print(f'created: {app_ini_example.as_posix()}')

        # Include app.py 
        app_py = proj_root / 'app.py'
        if not app_py.exists():
            with open(tpl_root / 'app.py', 'r') as r:
                contents = r.read()
            with open(app_py.as_posix(), 'w') as w:
                w.write(contents)
                print(f'created: {app_py.as_posix()}')

        # Include artisan
        artisan = proj_root / 'artisan'
        if not artisan.exists():
            with open(tpl_root / 'artisan', 'r') as r:
                contents = r.read()
            with open(artisan.as_posix(), 'w') as w:
                w.write(contents)
                os.chmod(artisan.as_posix(), 
                         os.stat(artisan.as_posix()).st_mode | 0o111)
                print(f'created: {artisan.as_posix()}')

        # Include requirements.txt
        requirements = proj_root / 'requirements.txt'
        if not requirements.exists():
            with open(tpl_root / 'requirements.txt', 'r') as r:
                contents = r.read()
            with open(requirements.as_posix(), 'w') as w:
                w.write(contents)
                print(f'created: {requirements.as_posix()}')

        app_py = proj_root / 'app.py'
        if not app_py.exists():
            with open(tpl_root / 'app.py', 'r') as r:
                contents = r.read()
            with open(app_py.as_posix(), 'w') as w:
                w.write(contents)
                print(f'created: {app_py.as_posix()}')

        cmd = Make()
        cmd(['controller', 'home'])

class Make(Command):

    NAME = 'make'
    DESC = 'Create a new resource'
    LONG_DESC = '''Create a new resource

Commands

command    [name] module name Ex. ProcessOrders
controller [name] module name Ex. orders
migration  [name] module name Ex. create_orders
model      [name] class name  Ex. OrderDetail
'''


    def __call__(self, args: list | None=[]):
        parser = argparse.ArgumentParser(
                description=self.LONG_DESC,
                exit_on_error=False,
                formatter_class=argparse.RawTextHelpFormatter,
                usage=self.NAME)
        parser.add_argument(
                'command',
                help='command',
                type=str)
        parser.add_argument(
                'name',
                help='resource name',
                type=str)
        try:
            parsed = parser.parse_args(args)
            if hasattr(self, parsed.command):
                getattr(self, parsed.command)(parsed.name)
            else:
                parser.print_help()
        except argparse.ArgumentError:
            parser.print_help()

    def command(self, name: str):
        tpl_root = Path(__file__).resolve().parent / 'templates'
        proj_root = Path().cwd()

        commands = proj_root / 'commands'
        if not commands.exists():
            commands.mkdir()

        snake = _camel_to_snake(name)
        path = commands / f'{snake}.py'
        if path.exists():
            print(f'{path} already exists.')
            return

        with open(tpl_root / 'make_command.py', 'r') as r:
            contents = r.read()

        with open(path.as_posix(), 'w') as w:
            w.write(contents.format(name=name, snake=snake))

        print(f'created: {path.as_posix()}')

    def controller(self, name: str):
        tpl_root = Path(__file__).resolve().parent / 'templates'
        proj_root = Path().cwd()

        controllers = proj_root / 'controllers'
        if not controllers.exists():
            controllers.mkdir()

        name = _camel_to_snake(name)
        path = controllers / f'{name}.py'
        if path.exists():
            print(f'{path} already exists.')
            return

        with open(tpl_root / 'make_controller.py', 'r') as r:
            contents = r.read()

        with open(path.as_posix(), 'w') as w:
            w.write(contents)

        print(f'created: {path.as_posix()}')

    def migration(self, name: str):
        tpl_root = Path(__file__).resolve().parent / 'templates'
        proj_root = Path().cwd()

        migrations = proj_root / 'migrations'
        if not migrations.exists():
            migrations.mkdir()

        prefix = datetime.now(UTC).strftime('%Y%m%d%H%M%S')
        name = f'{prefix}_{_camel_to_snake(name)}'
        path = migrations / f'{name}.py'

        with open(tpl_root / 'make_migration.py', 'r') as r:
            contents = r.read()

        with open(path.as_posix(), 'w') as w:
            w.write(contents.format(name=name))

        print(f'created: {path.as_posix()}')

    def model(self, name: str):
        tpl_root = Path(__file__).resolve().parent / 'templates'
        proj_root = Path().cwd()

        models = proj_root / 'models'
        if not models.exists():
            models.mkdir()

        file = _camel_to_snake(name)
        table = _pluralize(file)
        path = models / f'{file}.py'

        if path.exists():
            print(f'{path} already exists.')
            return

        with open(tpl_root / 'make_model.py', 'r') as r:
            contents = r.read()

        with open(path.as_posix(), 'w') as w:
            w.write(contents.format(name=name, table=table))

        print(f'created: {path.as_posix()}')

class Migrate(Command):

    NAME = 'migrate'
    DESC = 'Database migration commands'
    LONG_DESC = '''Database migration commands

Commands

apply                      Apply migrations
rollback --batch [batchid] Rollback batch
status                     View migrations status
'''

    def __call__(self, args: list | None=[]):
        parser = argparse.ArgumentParser(
                description=self.LONG_DESC,
                exit_on_error=False,
                formatter_class=argparse.RawTextHelpFormatter,
                usage=self.NAME)
        parser.add_argument(
                'command',
                help='command',
                type=str)
        parser.add_argument(
                '-b',
                '--batch',
                default=None,
                help='batch id for rollback',
                type=int)
        try:
            parsed = parser.parse_args(args)
            if hasattr(self, parsed.command):
                if parsed.command == 'rollback':
                    getattr(self, parsed.command)(parsed.batch)
                else:
                    getattr(self, parsed.command)()
            else:
                parser.print_help()
        except argparse.ArgumentError:
            parser.print_help()

    def apply(self):
        state = _get_migrations()
        unprocessed = [item for item in state if item['processed'] == False]
        if not unprocessed:
            return
        db = database()
        dt = datetime.now(UTC).strftime(DATETIME)
        def _max_batch(acc, item):
            batch = parseint(item.get('batch', ''))
            return batch if batch > acc else acc
        max_batch = reduce(_max_batch, state, 0)
        for item in unprocessed:
            migration = item['migration']
            print(f'{migration} migration started')
            module = importlib.import_module(item['module'])
            getattr(module, 'migrate')()
            sql = '''
                INSERT INTO pyteet_migrations
                (migration, batch, created_at, updated_at)
                VALUES(%s, %s, %s, %s)
            '''
            db.execute(sql, (migration, max_batch + 1, dt, dt))
            print(f'{migration} migration complete')

    def rollback(self, batch: int):
        state = _get_migrations()
        if not batch:
            def _max_batch(acc, item):
                batch = parseint(item.get('batch', ''))
                return batch if batch > acc else acc
            batch = reduce(_max_batch, state, 0)
        if not batch:
            return
        db = database()
        sql = '''
            SELECT
            *
            FROM pyteet_migrations
            WHERE batch = %s
        '''
        rows = db.fetchall(sql, (batch, ))
        for row in rows:
            migration = row['migration']
            print(f'{migration} rollback started')
            module = importlib.import_module(f'migrations.{migration}')
            getattr(module, 'rollback')()
            print(f'{migration} rollback complete')
        sql = '''
            DELETE FROM pyteet_migrations
            WHERE batch = %s
        '''
        db.execute(sql, (batch, ))

    def status(self):
        def print_sep(max_len):
            print('{}{}{}{}{}{}{}'.format(
                '+-',
                '-' * max_len[0],
                '-+-',
                '-' * max_len[1],
                '-+-',
                '-' * max_len[2],
                '-+'))
        def print_row(row, max_len):
            print('{}{}{}{}{}{}{}'.format(
                '| ',
                row[0].ljust(max_len[0]),
                ' | ',
                row[1].ljust(max_len[1]),
                ' | ',
                row[2].ljust(max_len[2]),
                ' |'))
        state = _get_migrations()
        header = ['Ran?', 'Migration', 'Batch']
        max_len = [len(x) for x in header]
        for k, v in enumerate(state):
            len_mgrtn = len(v['migration'])
            max_len[1] = len_mgrtn if len_mgrtn > max_len[1] else max_len[1]
            len_batch = len(str(v['batch']))
            max_len[2] = len_batch if len_batch > max_len[2] else max_len[2]
            state[k] = [
                    'Yes' if v['processed'] else 'No',
                    v['migration'],
                    str(v['batch']),
                    ]
        print_sep(max_len)
        print_row(header, max_len)
        print_sep(max_len)
        if state:
            for row in state:
                print_row(row, max_len)
            print_sep(max_len)

class PAT(Command):

    NAME = 'pat'
    DESC = 'Install PAT migration'

    def __call__(self, args: list | None=[]):
        parser = argparse.ArgumentParser(
                description=self.DESC,
                usage=self.NAME)
        parser.add_argument(
                '-i',
                '--install',
                action='store_true',
                help='install')
        parsed = parser.parse_args(args)
        if parsed.install:
            prefix = datetime.now(UTC).strftime('%Y%m%d%H%M%S')
            suffix = '_create_pyteet_pat'

            state = _get_migrations()
            for item in state:
                if item['migration'].endswith(suffix):
                    print('PAT migration already installed')
                    return

            tpl_root = Path(__file__).resolve().parent / 'templates'
            proj_root = Path().cwd()

            db = database()
            if db.driver == 'mysql':
                with open(tpl_root / 'pat_mysql.py', 'r') as r:
                    contents = r.read()
            elif db.driver == 'postgres':
                with open(tpl_root / 'pat_postgres.py', 'r') as r:
                    contents = r.read()
            elif db.driver == 'sqlite':
                with open(tpl_root / 'pat_sqlite.py', 'r') as r:
                    contents = r.read()
            else:
                raise ValueError(f'{db.driver} driver not supported.')

            migrations = proj_root / 'migrations'
            if not migrations.exists():
                migrations.mkdir()

            path = migrations / f'{prefix}{suffix}.py'
            with open(path.as_posix(), 'w') as w:
                w.write(contents.format(name=f'{prefix}{suffix}'))

            print(f'created: {path.as_posix()}')
        else:
            parser.print_help()

