from pyteet import database, Log

import importlib
from operator import itemgetter
from pathlib import Path

def migrations(connection=None):
    def find(state, migration):
        for idx, item in enumerate(state):
            if item['migration'] == migration:
                return idx
        return -1
    def validate(module):
        must_have = ('NAME', 'CONNECTION', 'migrate', 'rollback')
        for k in must_have:
            if not hasattr(module, k):
                return False
        return True
    # Get migrations
    state = []
    db = database(connection)
    try:
        sql = '''
            SELECT
            *
            FROM pyteet_migrations
        '''
        state = database(connection).fetchall(sql)
    except:
        Log.debug(f'pyteet_migrations does not exist, create.')
        if db.driver == 'mysql':
            sql = '''
                CREATE TABLE pyteet_migrations (
                    id bigint unsigned NOT NULL AUTO_INCREMENT,
                    migration varchar(255) NOT NULL,
                    batch bigint unsigned NOT NULL,
                    created_at timestamp NULL DEFAULT NULL,
                    updated_at timestamp NULL DEFAULT NULL,
                    PRIMARY KEY (id)
                )
            '''
        if db.driver == 'postgres':
            sql = '''
                CREATE TABLE pyteet_migrations (
                    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    migration varchar(255) NOT NULL,
                    batch bigint NOT NULL,
                    created_at timestamp NULL DEFAULT NULL,
                    updated_at timestamp NULL DEFAULT NULL
                )
            '''
        if db.driver == 'sqlite':
            sql = '''
                CREATE TABLE pyteet_migrations (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    migration TEXT NOT NULL,
                    batch INTEGER NOT NULL,
                    created_at TEXT NULL,
                    updated_at TEXT NULL
                )
            '''
        db.execute(sql)
    # Find migrations
    path = Path().cwd() / 'migrations'
    if path.exists():
        for file in path.iterdir():
            if not file.is_file():
                continue
            if file.suffix != '.py':
                continue
            module_name = f'migrations.{file.stem}'
            module = importlib.import_module(module_name)
            if not validate(module):
                continue
            migration = getattr(module, 'NAME')
            idx = find(state, migration)
            if idx >= 0:
                state[idx]['processed'] = True
            else:
                state.append({
                    'id': '',
                    'migration': migration,
                    'batch': '',
                    'processed': False,
                    'module': module_name,
                    })
    state = sorted(state, key=itemgetter('migration'))
    return state

