[app]
name = My App
env = production
version = 1.0

[database]
default = database_sqlite

# database driver must be one of:
# - mysql
# - postgres
# - sqlite

[database_mysql]
driver = mysql
host = 127.0.0.1
port = 3306
database = docker
username = root
password = docker
autocommit = True

[database_postgres]
driver = postgres
host = 127.0.0.1
port = 5432
database = docker
username = docker
password = docker
autocommit = True
#ssl_ca = [relative path to pem]
#ssl_verify_identity = True

[database_sqlite]
driver = sqlite
database = app.db
autocommit = True

