from pyteet import database

NAME = '20260706172438_create_pyteet_pat'
CONNECTION = None # Use default database connection

def migrate():
    db = database(CONNECTION)
    if db.driver == 'mysql':
        sql = '''
            CREATE TABLE pyteet_pat (
                id bigint unsigned NOT NULL AUTO_INCREMENT,
                tokenable_module varchar(255) NOT NULL,
                tokenable_class varchar(255) NOT NULL,
                tokenable_id bigint unsigned NOT NULL,
                name varchar(255) NOT NULL,
                token varchar(255) NOT NULL,
                abilities varchar(255) NOT NULL,
                last_used_at timestamp NULL DEFAULT NULL,
                created_at timestamp NULL DEFAULT NULL,
                updated_at timestamp NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        '''
        db.execute(sql)
    if db.driver == 'postgres':
        sql = '''
            CREATE TABLE pyteet_pat (
                id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                tokenable_module varchar(255) NOT NULL,
                tokenable_class varchar(255) NOT NULL,
                tokenable_id bigint NOT NULL,
                name varchar(255) NOT NULL,
                token varchar(255) NOT NULL,
                abilities varchar(255) NOT NULL,
                last_used_at timestamp NULL DEFAULT NULL,
                created_at timestamp NULL DEFAULT NULL,
                updated_at timestamp NULL DEFAULT NULL
            )
        '''
        db.execute(sql)
    if db.driver == 'sqlite':
        sql = '''
            CREATE TABLE pyteet_pat (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                tokenable_module TEXT NOT NULL,
                tokenable_class TEXT NOT NULL,
                tokenable_id INTEGER NOT NULL,
                name TEXT NOT NULL,
                token TEXT NOT NULL,
                abilities TEXT NOT NULL,
                last_used_at TEXT NULL,
                created_at TEXT NULL,
                updated_at TEXT NULL
            )
        '''
        db.execute(sql)

def rollback():
    db = database(CONNECTION)
    sql = '''
        DROP TABLE pyteet_pat
    '''
    db.execute(sql)