from pyteet import database

NAME = '20260706193525_create_contacts'
CONNECTION = None # Use default database connection

def migrate():
    db = database(CONNECTION)
    if db.driver == 'mysql':
        sql = '''
            CREATE TABLE contacts (
                id bigint unsigned NOT NULL AUTO_INCREMENT,
                email varchar(255) NOT NULL,
                password varchar(255) NOT NULL,
                firstname varchar(255) NOT NULL,
                lastname varchar(255) NOT NULL,
                last_login timestamp NULL DEFAULT NULL,
                created_at timestamp NULL DEFAULT NULL,
                updated_at timestamp NULL DEFAULT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY email (email(191))
            )
        '''
        db.execute(sql)
    if db.driver == 'postgres':
        sql = '''
            CREATE TABLE contacts (
                id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                email varchar(255) NOT NULL,
                password varchar(255) NOT NULL,
                firstname varchar(255) NOT NULL,
                lastname varchar(255) NOT NULL,
                last_login timestamp NULL DEFAULT NULL,
                created_at timestamp NULL DEFAULT NULL,
                updated_at timestamp NULL DEFAULT NULL
            )
        '''
        db.execute(sql)
        sql = '''
            CREATE UNIQUE INDEX contacts_idx_email ON contacts(email)
        '''
        db.execute(sql)
    if db.driver == 'sqlite':
        sql = '''
            CREATE TABLE contacts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email TEXT NOT NULL,
                password TEXT NOT NULL,
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                last_login TEXT NULL,
                created_at TEXT NULL,
                updated_at TEXT NULL
            )
        '''
        db.execute(sql)
        sql = '''
            CREATE UNIQUE INDEX contacts_idx_email ON contacts(email)
        '''
        db.execute(sql)

def rollback():
    db = database(CONNECTION)
    sql = '''
        DROP TABLE contacts
    '''
    db.execute(sql)
